// Named Lucide data imports keep icons framework-free and tree-shakable.
import {
  Activity,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  Blocks,
  Bold,
  Building2,
  CakeSlice,
  Calendar,
  CalendarCheck2,
  CalendarDays,
  CalendarPlus,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  ClipboardPaste,
  CloudUpload,
  Code2,
  Cookie,
  Copy,
  Database,
  DatabaseZap,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck2,
  Fingerprint,
  Folder,
  FolderOpen,
  Gift,
  GripHorizontal,
  GripVertical,
  Heading1,
  Heading2,
  Heading3,
  Heart,
  House,
  Info,
  Italic,
  KeyRound,
  LayoutDashboard,
  Library,
  List,
  ListChecks,
  ListOrdered,
  Loader,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquareText,
  Minus,
  MousePointer2,
  PackageCheck,
  Palette,
  PanelsTopLeft,
  PartyPopper,
  Pencil,
  Pilcrow,
  Pin,
  Plus,
  Quote,
  Radio,
  Redo2,
  RotateCcw,
  Route,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Star,
  StickyNote,
  Strikethrough,
  Sun,
  Table2,
  TableProperties,
  TextQuote,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Type,
  Underline,
  Undo2,
  User,
  UserRound,
  Users,
  X,
  type IconNode,
} from "lucide";

export type { IconNode };

export const icons: Record<string, IconNode> = {
  "activity": Activity,
  "align-center": AlignCenter,
  "align-justify": AlignJustify,
  "align-left": AlignLeft,
  "align-right": AlignRight,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  "bell": Bell,
  "blocks": Blocks,
  "bold": Bold,
  "building-2": Building2,
  "cake-slice": CakeSlice,
  "calendar": Calendar,
  "calendar-check-2": CalendarCheck2,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "camera": Camera,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle": Circle,
  "circle-check": CircleCheck,
  "clipboard-paste": ClipboardPaste,
  "cloud-upload": CloudUpload,
  "code-2": Code2,
  "cookie": Cookie,
  "copy": Copy,
  "database": Database,
  "database-zap": DatabaseZap,
  "download": Download,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "file": File,
  "file-check-2": FileCheck2,
  "fingerprint": Fingerprint,
  "folder": Folder,
  "folder-open": FolderOpen,
  "gift": Gift,
  "grip-horizontal": GripHorizontal,
  "grip-vertical": GripVertical,
  "heading-1": Heading1,
  "heading-2": Heading2,
  "heading-3": Heading3,
  "heart": Heart,
  "house": House,
  "info": Info,
  "italic": Italic,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  "library": Library,
  "list": List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  "loader": Loader,
  "loader-circle": LoaderCircle,
  "lock": Lock,
  "lock-keyhole": LockKeyhole,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "map-pin": MapPin,
  "megaphone": Megaphone,
  "message-circle": MessageCircle,
  "message-square-text": MessageSquareText,
  "minus": Minus,
  "mouse-pointer-2": MousePointer2,
  "package-check": PackageCheck,
  "palette": Palette,
  "panels-top-left": PanelsTopLeft,
  "party-popper": PartyPopper,
  "pencil": Pencil,
  "pilcrow": Pilcrow,
  "pin": Pin,
  "plus": Plus,
  "quote": Quote,
  "radio": Radio,
  "redo-2": Redo2,
  "rotate-ccw": RotateCcw,
  "route": Route,
  "save": Save,
  "scissors": Scissors,
  "search": Search,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  "sliders-horizontal": SlidersHorizontal,
  "snowflake": Snowflake,
  "sparkles": Sparkles,
  "star": Star,
  "sticky-note": StickyNote,
  "strikethrough": Strikethrough,
  "sun": Sun,
  "table-2": Table2,
  "table-properties": TableProperties,
  "text-quote": TextQuote,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "truck": Truck,
  "type": Type,
  "underline": Underline,
  "undo-2": Undo2,
  "user": User,
  "user-round": UserRound,
  "users": Users,
  "x": X,
};
